server:
  port: 8080
spring:
  config:
    import: optional:classpath:application-secret.yml
  application:
# ... (rest of file with placeholders)
    username: root
    password: ${GNS_DB_PASSWORD:root} # Overridden by secret.yml
# ...
  mail:
    host: smtp.qq.com
    username: yubolee1217@qq.com
    password: ${GNS_MAIL_PASSWORD} # Overridden by secret.yml
# ...
app:
  security:
    jwt-secret: ${GNS_JWT_SECRET:change-me} # Overridden by secret.yml
# ...
ai:
  baidu:
    api-key: ${GNS_BAIDU_API_KEY} # Overridden by secret.yml
    name: universal-notification-system
  datasource:
    url: jdbc:mysql://localhost:3306/gns?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${GNS_DB_USER:root}
    password: "" # Loaded from application-secret.yml
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 2
  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: true
    repair-on-migrate: true
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.qq.com
    username: yubolee1217@qq.com
    password: "" # Loaded from application-secret.yml
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    from: yubolee1217@qq.com
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
app:
  security:
    jwt-secret: change-me-in-secret-yml # Loaded from application-secret.yml
    jwt-expiration-hours: 24
  notification:
    redis-stream-key: gns:notifications
    consumer-group: gns-workers
    consumer-name: gns-worker-1
  scheduler:
    type: redis # Options: db, redis
ai:
  baidu:
    # Obtain free keys from: https://console.bce.baidu.com/
    api-key: "" # Loaded from application-secret.yml
logging:
  level:
    root: INFO
    com.gns.notification: DEBUG
